# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/brandon/Documents/Vivado_Projects/T_Rex_Runner/T_Rex_Runner.srcs/sources_1/ip/obstacleROM/obstacleROM.xci
# IP: The module: 'obstacleROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/brandon/Documents/Vivado_Projects/T_Rex_Runner/T_Rex_Runner.srcs/sources_1/ip/obstacleROM/obstacleROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'obstacleROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/brandon/Documents/Vivado_Projects/T_Rex_Runner/T_Rex_Runner.srcs/sources_1/ip/obstacleROM/obstacleROM.xci
# IP: The module: 'obstacleROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/brandon/Documents/Vivado_Projects/T_Rex_Runner/T_Rex_Runner.srcs/sources_1/ip/obstacleROM/obstacleROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'obstacleROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
